chris_contacter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacter.urls')),
]

contacter/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ConversationCreateView.as_view(), name='conversation-create'),
    path('conversations/', views.ConversationListView.as_view(), name='conversation-list'),
]

contacter/models.py
from django.db import models

UNSENT = 'Unsent'
CHAT = 'Chat'
EMAIL = 'Email'
TEXT = 'Text'
CALL = 'Call'
PRIORITY_CHOICES = (
    (0, UNSENT),
    # (10, CHAT),  # NYI due to insufficient Hangouts support for unsolicited messages
    (20, EMAIL),
    (30, TEXT),
)


class Conversation(models.Model):
    message = models.TextField()
    priority = models.PositiveIntegerField(choices=PRIORITY_CHOICES, help_text='Highest service to try')
    status = models.PositiveIntegerField(choices=PRIORITY_CHOICES, default=0, help_text='Highest service tried')
    sent = models.DateTimeField(blank=True, null=True)
    responded = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ('-sent',)

    def __str__(self):
        return f'{self.get_status_display()}: {self.message[:50]}'

contacter/views.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from .models import Conversation


class ConversationCreateView(CreateView):
    model = Conversation
    fields = ('message', 'priority')
    success_url = reverse_lazy('conversation-list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.helper = FormHelper()
        form.helper.add_input(Submit('submit', 'Send!', css_class='btn-primary'))
        return form


class ConversationListView(ListView):
    model = Conversation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['priority_help_text'] = self.model._meta.get_field('priority').help_text
        context['status_help_text'] = self.model._meta.get_field('status').help_text
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'tree-boi.png' %}"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Chris Contacter</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-10">
          <h1 class="mt-2">Chris Contacter</h1>
          <small>For all your Chris-contacting needs.</small>
          <hr class="mt-1 mb-4">
          <a class="btn btn-primary mb-4 ml-4" href="{% url 'conversation-create' %}" role="button">Add</a>
          <a class="btn btn-primary mb-4 ml-2" href="{% url 'conversation-list' %}" role="button">View</a>
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    <footer class="footer fixed-bottom">
      <div class="container text-muted text-right mb-2">
        Built with grudging respect in Philadelphia.
      </div>
    </footer>
  </body>
</html>

templates/contacter/conversation_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% crispy form %}
{% endblock %}

templates/contacter/conversation_list.html
{% extends 'base.html' %}

{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th>Message</th>
        <th title="{{ priority_help_text }}">Priority</th>
        <th title="{{ status_help_text }}">Status</th>
        <th>Sent</th>
        <th>Responded</th>
      </tr>
    </thead>
    <tbody>
      {% for conversation in conversation_list %}
        <tr class="{{ conversation.get_status_display|lower }}{% if conversation.responded %} responded{% endif %}">
          <td>{{ conversation.message }}</td>
          <td>{{ conversation.get_priority_display }}</td>
          <td>{{ conversation.get_status_display }}</td>
          <td>{{ conversation.sent|default:"" }}</td>
          <td>{{ conversation.responded|default:"" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}